# Generated by Django 4.1.2 on 2022-11-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBCompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Company',
        ),
    ]
